{% set name = "setuptools-git-version" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/setuptools-git-version-{{ version }}.zip
  sha256: 82cf7ab80272e20b7cae81d907e0adf295ef7a1f735418c046ae7f40f5861e15

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - setuptools >=8.0

test:
  imports:
    - setuptools_git_version
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyfidelity/setuptools-git-version
  summary: Automatically set package version from Git.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
